default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nsehe_development

test:
  <<: *default
  database: nsehe_test

production:
  <<: *default
  database: nsehe_production
  username: nsehe
  password: <%= ENV['NSEHE_DATABASE_PASSWORD'] %>
